### ISSUE TITLE
compile python wrapper error

### ISSUE THREAD

**Issue by zabcd117** [OpenKinect/libfreenect#287]
hi,
when i compile openkinect with python wrapper, i got some error as follows:

[ 20%] Built target freenect
[ 40%] Built target freenectstatic
[ 44%] Built target freenect_sync
[ 48%] Built target glpclview
[ 52%] Built target glview
[ 56%] Built target hiview
[ 60%] Built target regtest
[ 64%] Built target regview
[ 68%] Built target tiltdemo
[ 72%] Built target fakenect
[ 76%] Built target record
[ 80%] Built target freenect_sync_static
[ 84%] Built target cppview
[ 88%] Built target freenect_cv
[ 92%] Built target cvdemo
Linking C shared module freenect.so
Undefined symbols for architecture x86_64:
  "__Py_NoneStruct", referenced from:
      ___pyx_tp_new_8freenect_DevPtr in freenect.c.o
      ___pyx_tp_clear_8freenect_DevPtr in freenect.c.o
      ___pyx_pw_8freenect_57sync_stop in freenect.c.o
      ___Pyx_Raise in freenect.c.o
      ___Pyx_WriteUnraisable in freenect.c.o
      ___pyx_f_8freenect_video_cb in freenect.c.o
      ___pyx_f_8freenect_depth_cb in freenect.c.o
      ...
  "__PyThreadState_Current", referenced from:
      ___Pyx_ExceptionReset in freenect.c.o
      ___Pyx_Raise in freenect.c.o
      ___Pyx_WriteUnraisable in freenect.c.o
      ___Pyx_AddTraceback in freenect.c.o
      ___pyx_pw_8freenect_45runloop in freenect.c.o
      ___pyx_pw_8freenect_47base_runloop in freenect.c.o
  "_PyDict_Next", referenced from:
      ___Pyx_ParseOptionalKeywords in freenect.c.o
  "_PyString_Type", referenced from:
      ___Pyx_ParseOptionalKeywords in freenect.c.o
  "__PyString_Eq", referenced from:
      ___Pyx_ParseOptionalKeywords in freenect.c.o
  "_PyExc_TypeError", referenced from:
      ___Pyx_ParseOptionalKeywords in freenect.c.o
      ___Pyx_PyInt_AsLong in freenect.c.o
      ___Pyx_Raise in freenect.c.o
      ___Pyx_ImportType in freenect.c.o
      ___pyx_pw_8freenect_39open_device in freenect.c.o
      ___pyx_pw_8freenect_1set_depth_mode in freenect.c.o
      ___pyx_pw_8freenect_3set_video_mode in freenect.c.o
      ...
      ...
      ...
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
make[1]: *** [wrappers/python/freenect.so] Error 1
make: *** [cython_freenect/fast] Error 2

it looks like cython module has got some error, but i don't konw to fix it. i work in macosx10.7.3, cython installed by macports

**Comment by piedar** [comment]
Missing python reference fixed by 476dec9.
